### ISSUE TITLE
Support for Postgres citext datatype

### ISSUE THREAD

**Issue by entertainment-inteligence** [mohaseeb/beam-nuggets#16]
Great work on these beam nuggets! 

I successfully used the RelationalDB read to connect to my PostgreSQL DB and save the table contents to a JSON file. 

One thing I noticed, however, is that this doesn't support the Postgres citext datatype. I found a workaround by using this: https://github.com/mahmoudimus/sqlalchemy-citext

I wanted to bring to your attention in case you can incorporate into the nugget. I would attempt a contribution / pull request but I am new to Python.

**Comment by mohaseeb** [comment]
Happy it worked for you!

You can submit a PR as you suggested.
