### ISSUE TITLE
Using Runtime Parameters 

### ISSUE THREAD

**Issue by pebcakerror** [mohaseeb/beam-nuggets#21]
Does Beam Nuggets support Runtime Parameters? 

Is it possible to parameterize the `SourceConfiguration` and `table_name` 

https://cloud.google.com/dataflow/docs/guides/templates/creating-templates

**Comment by mohaseeb** [comment]
Hi @pebcakerror, as you may already know by now, beam nuggets doesn't support runtime parameters.
Feel free add support for that :)

`Is it possible to parameterize the SourceConfiguration and table_name`
other than Dataflow's runtime parameters? nothing in the current implementation supports that. I can think of a simpler way than using runtime parameters in the Dataflow runner case.
