### ISSUE TITLE
KafkaConsume forces UTF-8 decoding

### ISSUE THREAD

**Issue by shivangkumar** [mohaseeb/beam-nuggets#33]
# Description
The KafkaConsume DoFn uses the default decoder for each message it receives ([code here](https://github.com/mohaseeb/beam-nuggets/blob/master/beam_nuggets/io/kafkaio.py#L69)). This forces messages being pulled from a topic to be decoded using utf-8.
While this is unlikely to cause an issue for most use cases, the function is rendered unusable if the encoding is anything but utf-8.

# Proposal
Using utf-8 decoding as a default is still a great idea, but users should have the ability to override this default and provide their own decoder function which can be invoked before returning the message.

**Comment by mohaseeb** [comment]
Fixed by https://github.com/mohaseeb/beam-nuggets/pull/34 made by @shivangkumar
