### ISSUE TITLE
pg8000 1.16.6 or greater is required [while running 'Writing to DB/ParDo(_WriteToRelationalDBFn)']

### ISSUE THREAD

**Issue by 3amrouchmasmoudi** [mohaseeb/beam-nuggets#44]
I am running write_to_relational_db.py  and I am facing a dependency problem : 

`Error message from worker: Traceback (most recent call last): File "apache_beam/runners/common.py", line 1257, in apache_beam.runners.common.DoFnRunner._invoke_bundle_method File "apache_beam/runners/common.py", line 502, in apache_beam.runners.common.DoFnInvoker.invoke_start_bundle File "apache_beam/runners/common.py", line 508, in apache_beam.runners.common.DoFnInvoker.invoke_start_bundle File "/usr/local/lib/python3.7/site-packages/beam_nuggets/io/relational_db.py", line 177, in start_bundle self._db = SqlAlchemyDB(self.source_config) File "/usr/local/lib/python3.7/site-packages/beam_nuggets/io/relational_db_api.py", line 249, in __init__ self._SessionClass = sessionmaker(bind=create_engine(self._source.url)) File "<string>", line 2, in create_engine File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned return fn(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 561, in create_engine dialect = dialect_cls(**dialect_args) File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/pg8000.py", line 395, in __init__ raise NotImplementedError("pg8000 1.16.6 or greater is required") NotImplementedError: pg8000 1.16.6 or greater is required During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/dataflow_worker/batchworker.py", line 651, in do_work work_executor.execute() File "/usr/local/lib/python3.7/site-packages/dataflow_worker/executor.py", line 179, in execute op.start() File "apache_beam/runners/worker/operations.py", line 704, in apache_beam.runners.worker.operations.DoOperation.start File "apache_beam/runners/worker/operations.py", line 706, in apache_beam.runners.worker.operations.DoOperation.start File "apache_beam/runners/worker/operations.py", line 708, in apache_beam.runners.worker.operations.DoOperation.start File "apache_beam/runners/common.py", line 1274, in apache_beam.runners.common.DoFnRunner.start File "apache_beam/runners/common.py", line 1259, in apache_beam.runners.common.DoFnRunner._invoke_bundle_method File "apache_beam/runners/common.py", line 1306, in apache_beam.runners.common.DoFnRunner._reraise_augmented File "apache_beam/runners/common.py", line 1257, in apache_beam.runners.common.DoFnRunner._invoke_bundle_method File "apache_beam/runners/common.py", line 502, in apache_beam.runners.common.DoFnInvoker.invoke_start_bundle File "apache_beam/runners/common.py", line 508, in apache_beam.runners.common.DoFnInvoker.invoke_start_bundle File "/usr/local/lib/python3.7/site-packages/beam_nuggets/io/relational_db.py", line 177, in start_bundle self._db = SqlAlchemyDB(self.source_config) File "/usr/local/lib/python3.7/site-packages/beam_nuggets/io/relational_db_api.py", line 249, in __init__ self._SessionClass = sessionmaker(bind=create_engine(self._source.url)) File "<string>", line 2, in create_engine File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned return fn(*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 561, in create_engine dialect = dialect_cls(**dialect_args) File "/usr/local/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/pg8000.py", line 395, in __init__ raise NotImplementedError("pg8000 1.16.6 or greater is required") NotImplementedError: pg8000 1.16.6 or greater is required [while running 'Writing to DB/ParDo(_WriteToRelationalDBFn)']`

Can we change the version of pg8000 ?

**Comment by mohaseeb** [comment]
This is now fixed in `beam-nuggets==0.18.1`
